<script type="text/javascript" src="/admin/public/mydate/calendar.js"></script>
<script type="text/javascript" src="/admin/public/mydate/calendar-setup.js"></script>
<script type="text/javascript" src="/admin/public/mydate/lang/calendar-en.js"></script>
<link rel="stylesheet" type="text/css" media="all" href="/admin/public/mydate/skins/aqua/theme.css" title="Aqua" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-blue.css" title="winter" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-blue2.css" title="blue" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-brown.css" title="summer" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-green.css" title="green" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-win2k-1.css" title="win2k-1" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-win2k-2.css" title="win2k-2" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-win2k-cold-1.css" title="win2k-cold-1" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-win2k-cold-2.css" title="win2k-cold-2" />
<link rel="alternate stylesheet" type="text/css" media="all" href="/admin/public/mydate/calendar-system.css" title="system" />